// primesya
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18a : 5th-December-2016 Unix 3.13.0.65// 10/02/2017 17:08:09
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe csharp/primes_offchip.exe -res2-loadstore-port-count=0 -vnl=primes_offchip.v -vnl-rootmodname=primes_offchip csharp/KSubs2_Director.dll -vnl-resets=synchronous -kiwic-finish=disable -vnl-roundtrip=disable -kiwic-register-colours=1 -bevelab-default-pause-mode=bblock -fp-fl-sp-mul=4

#include "primesya.h"

// opath operation: 10: cgen2

 void primesya::exe014()
 { 
  //  Method no 0 mname=primesya
    if (xpc10nz==22/*22:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void primesya::exe114()
 { 
  //  Method no 1 mname=primesya
    if (xpc10nz==21/*21:xpc10nz*/)
    xpc10nz = (22/*22:xpc10nz*/);
}

 void primesya::exe214()
 { 
  //  Method no 2 mname=primesya
    if (xpc10nz==20/*20:xpc10nz*/)
    xpc10nz = (18/*18:xpc10nz*/);
}

 void primesya::exe310()
 { 
  //  Method no 3 mname=primesya
    if (xpc10nz==19/*19:xpc10nz*/)
    xpc10nz = (20/*20:xpc10nz*/);
}

 void primesya::exe410()
 { 
  //  Method no 4 mname=primesya
    if (primesya_T404_Main_T404_Main_V_4_GP<1000&&xpc10nz==18/*18:xpc10nz*/)
    xpc10nz = (19/*19:xpc10nz*/);
}

 void primesya::exe510()
 { 
  //  Method no 5 mname=primesya
    if (primesya_T404_Main_T404_Main_V_4_GP>=1000&&xpc10nz==18/*18:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void primesya::exe610()
 { 
  //  Method no 6 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP+primesya_T404_Main_T404_Main_V_2_GP<1000&&xpc10nz==17/*17:xpc10nz*/)
    xpc10nz = (18/*18:xpc10nz*/);
}

 void primesya::exe710()
 { 
  //  Method no 7 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP+primesya_T404_Main_T404_Main_V_2_GP>=1000&&xpc10nz==17/*17:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void primesya::exe810()
 { 
  //  Method no 8 mname=primesya
    if (xpc10nz==16/*16:xpc10nz*/)
    xpc10nz = (7/*7:xpc10nz*/);
}

 void primesya::exe910()
 { 
  //  Method no 9 mname=primesya
    if (xpc10nz==15/*15:xpc10nz*/&&!__BOOL_CC_SCALbx10_ARA0_RDD0)
    if ((xpc10nz==15/*15:xpc10nz*/&&!__BOOL_CC_SCALbx10_ARA0_RDD0)||(xpc10nz!=15/*15:xpc10nz*/&&!BOOLCCSCALbx10ARA0RRh10hold))
    xpc10nz = (16/*16:xpc10nz*/);
}

 void primesya::exe1010()
 { 
  //  Method no 10 mname=primesya
    if (xpc10nz==15/*15:xpc10nz*/&&__BOOL_CC_SCALbx10_ARA0_RDD0)
    if ((xpc10nz==15/*15:xpc10nz*/&&__BOOL_CC_SCALbx10_ARA0_RDD0)||(xpc10nz!=15/*15:xpc10nz*/&&BOOLCCSCALbx10ARA0RRh10hold))
    xpc10nz = (16/*16:xpc10nz*/);
}

 void primesya::exe1110()
 { 
  //  Method no 11 mname=primesya
    if (xpc10nz==14/*14:xpc10nz*/)
    xpc10nz = (15/*15:xpc10nz*/);
}

 void primesya::exe1210()
 { 
  //  Method no 12 mname=primesya
    if (xpc10nz==13/*13:xpc10nz*/)
    xpc10nz = (12/*12:xpc10nz*/);
}

 void primesya::exe1310()
 { 
  //  Method no 13 mname=primesya
    if (xpc10nz==12/*12:xpc10nz*/)
    xpc10nz = (13/*13:xpc10nz*/);
}

 void primesya::exe1410()
 { 
  //  Method no 14 mname=primesya
    if (xpc10nz==11/*11:xpc10nz*/)
    xpc10nz = (12/*12:xpc10nz*/);
}

 void primesya::exe1510()
 { 
  //  Method no 15 mname=primesya
    if (xpc10nz==10/*10:xpc10nz*/)
    xpc10nz = (11/*11:xpc10nz*/);
}

 void primesya::exe1610()
 { 
  //  Method no 16 mname=primesya
    if (xpc10nz==9/*9:xpc10nz*/)
    xpc10nz = (10/*10:xpc10nz*/);
}

 void primesya::exe1710()
 { 
  //  Method no 17 mname=primesya
    if (xpc10nz==8/*8:xpc10nz*/)
    xpc10nz = (9/*9:xpc10nz*/);
}

 void primesya::exe1810()
 { 
  //  Method no 18 mname=primesya
    if (primesya_T404_Main_T404_Main_V_4_GP<1000&&xpc10nz==7/*7:xpc10nz*/)
    xpc10nz = (14/*14:xpc10nz*/);
}

 void primesya::exe1910()
 { 
  //  Method no 19 mname=primesya
    if (primesya_T404_Main_T404_Main_V_4_GP>=1000&&xpc10nz==7/*7:xpc10nz*/)
    xpc10nz = (8/*8:xpc10nz*/);
}

 void primesya::exe2010()
 { 
  //  Method no 20 mname=primesya
    if (xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (7/*7:xpc10nz*/);
}

 void primesya::exe2110()
 { 
  //  Method no 21 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP<1000&&xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (17/*17:xpc10nz*/);
}

 void primesya::exe2210()
 { 
  //  Method no 22 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP>=1000&&xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void primesya::exe2310()
 { 
  //  Method no 23 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP<1000&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (21/*21:xpc10nz*/);
}

 void primesya::exe2410()
 { 
  //  Method no 24 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP>=1000&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void primesya::exe2510()
 { 
  //  Method no 25 mname=primesya
    if (xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void primesya::exe2610()
 { 
  //  Method no 26 mname=primesya
    if (xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void primesya::exe2710()
 { 
  //  Method no 27 mname=primesya
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void primesya::exe2810()
 { 
  //  Method no 28 mname=primesya
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void primesya::exe2910()
 { 
  //  Method no 29 mname=primesya
    if (xpc10nz==0/*0:xpc10nz*/)
     hpr_writeln("%s%i", "Primes Up To ", 1000);
}

 void primesya::exe3010()
 { 
  //  Method no 30 mname=primesya
    if (xpc10nz==0/*0:xpc10nz*/)
     hpr_KppMark("START", "INITIALISE");
}

 void primesya::exe3110()
 { 
  //  Method no 31 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP>=1000&&xpc10nz==4/*4:xpc10nz*/)
     hpr_KppMark("wp2", "CROSSOFF");
}

 void primesya::exe3210()
 { 
  //  Method no 32 mname=primesya
    if (xpc10nz==6/*6:xpc10nz*/)
     hpr_writeln("Now counting");
}

 void primesya::exe3310()
 { 
  //  Method no 33 mname=primesya
    if (xpc10nz==6/*6:xpc10nz*/)
     hpr_KppMark("wp3", "COUNTING");
}

 void primesya::exe3410()
 { 
  //  Method no 34 mname=primesya
    if (primesya_T404_Main_T404_Main_V_4_GP>=1000&&xpc10nz==7/*7:xpc10nz*/)
     hpr_writeln("Optimisation variant=%u (count1 is %u).", 0, 2);
}

 void primesya::exe3510()
 { 
  //  Method no 35 mname=primesya
    if (primesya_T404_Main_T404_Main_V_4_GP>=1000&&xpc10nz==7/*7:xpc10nz*/)
     hpr_writeln("There are %d primes below the natural number %u.", count, 1000);
}

 void primesya::exe3610()
 { 
  //  Method no 36 mname=primesya
    if (xpc10nz==9/*9:xpc10nz*/)
     hpr_KppMark("FINISH");
}

 void primesya::exe3710()
 { 
  //  Method no 37 mname=primesya
    if (xpc10nz==16/*16:xpc10nz*/)
     hpr_writeln("Tally counting %u %d", primesya_T404_Main_T404_Main_V_4_GP, count);
}

 void primesya::exe3810()
 { 
  //  Method no 38 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP+primesya_T404_Main_T404_Main_V_2_GP>=1000&&xpc10nz==17/*17:xpc10nz*/)
     hpr_writeln("Skip out on square");
}

 void primesya::exe3910()
 { 
  //  Method no 39 mname=primesya
    if (primesya_T404_Main_T404_Main_V_4_GP<1000&&xpc10nz==18/*18:xpc10nz*/)
     hpr_writeln("Cross off %u %u   (count1=%u)", primesya_T404_Main_T404_Main_V_2_GP, primesya_T404_Main_T404_Main_V_4_GP, 2);
}

 void primesya::exe4010()
 { 
  //  Method no 40 mname=primesya
    if (xpc10nz==21/*21:xpc10nz*/)
     hpr_writeln("Setting initial array flag to hold : addr=%u readback=%d", primesya_T404_Main_T404_Main_V_2_GP, 0x1);
}

 void primesya::exe4110()
 { 
  //  Method no 41 mname=primesya
    BOOLCCSCALbx10ARA0RRh10shot0 = (xpc10nz==14/*14:xpc10nz*/);
}

 void primesya::exe4210()
 { 
  //  Method no 42 mname=primesya
    __BOOL_CC_SCALbx10_ARA0_WEN0 = (((xpc10nz==21/*21:xpc10nz*/||xpc10nz==1/*1:xpc10nz*/||xpc10nz==19/*19:xpc10nz*/)?1:0));
}

 void primesya::exe4310()
 { 
  //  Method no 43 mname=primesya
    __BOOL_CC_SCALbx10_ARA0_REN0 = (((xpc10nz==14/*14:xpc10nz*/)?1:0));
}

 void primesya::exe4410()
 { 
  //  Method no 44 mname=primesya
    if (BOOLCCSCALbx10ARA0RRh10shot0)
    BOOLCCSCALbx10ARA0RRh10hold = (__BOOL_CC_SCALbx10_ARA0_RDD0);
}

 void primesya::exe4510()
 { 
  //  Method no 45 mname=primesya
    if (xpc10nz==0/*0:xpc10nz*/)
    elimit = (1000);
}

 void primesya::exe4610()
 { 
  //  Method no 46 mname=primesya
    if (xpc10nz==0/*0:xpc10nz*/)
    pio_rdata = (0);
}

 void primesya::exe4710()
 { 
  //  Method no 47 mname=primesya
    if (xpc10nz==0/*0:xpc10nz*/)
    design_serial_number = (0x221102);
}

 void primesya::exe4810()
 { 
  //  Method no 48 mname=primesya
    if (xpc10nz==0/*0:xpc10nz*/)
    finished = (0x0);
}

 void primesya::exe4910()
 { 
  //  Method no 49 mname=primesya
    if (xpc10nz==0/*0:xpc10nz*/)
    edesign = (4032);
}

 void primesya::exe5010()
 { 
  //  Method no 50 mname=primesya
    if (xpc10nz==0/*0:xpc10nz*/)
    evariant = (0);
}

 void primesya::exe5110()
 { 
  //  Method no 51 mname=primesya
    if (xpc10nz==0/*0:xpc10nz*/)
    count = (0x0);
}

 void primesya::exe5210()
 { 
  //  Method no 52 mname=primesya
    if (xpc10nz==1/*1:xpc10nz*/)
    __BOOL_CC_SCALbx10_ARA0_WRD0 = (0<volume);
}

 void primesya::exe5310()
 { 
  //  Method no 53 mname=primesya
    if (xpc10nz==1/*1:xpc10nz*/)
    __BOOL_CC_SCALbx10_ARA0_AD0 = (0);
}

 void primesya::exe5410()
 { 
  //  Method no 54 mname=primesya
    if (xpc10nz==3/*3:xpc10nz*/)
    count = (0x0);
}

 void primesya::exe5510()
 { 
  //  Method no 55 mname=primesya
    if (xpc10nz==3/*3:xpc10nz*/)
    primesya_T404_Main_T404_Main_V_2_GP = (0);
}

 void primesya::exe5610()
 { 
  //  Method no 56 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP>=1000&&xpc10nz==4/*4:xpc10nz*/)
    primesya_T404_Main_T404_Main_V_2_GP = (2);
}

 void primesya::exe5710()
 { 
  //  Method no 57 mname=primesya
    if (xpc10nz==6/*6:xpc10nz*/)
    primesya_T404_Main_T404_Main_V_4_GP = (0);
}

 void primesya::exe5810()
 { 
  //  Method no 58 mname=primesya
    if (xpc10nz==10/*10:xpc10nz*/)
    finished = (0x1);
}

 void primesya::exe5910()
 { 
  //  Method no 59 mname=primesya
    if (xpc10nz==14/*14:xpc10nz*/)
    __BOOL_CC_SCALbx10_ARA0_AD0 = (primesya_T404_Main_T404_Main_V_4_GP);
}

 void primesya::exe6010()
 { 
  //  Method no 60 mname=primesya
    if (xpc10nz==15/*15:xpc10nz*/&&__BOOL_CC_SCALbx10_ARA0_RDD0)
    if ((xpc10nz==15/*15:xpc10nz*/&&__BOOL_CC_SCALbx10_ARA0_RDD0)||(xpc10nz!=15/*15:xpc10nz*/&&BOOLCCSCALbx10ARA0RRh10hold))
    count = ((unsigned int)(1+count));
}

 void primesya::exe6110()
 { 
  //  Method no 61 mname=primesya
    if (xpc10nz==16/*16:xpc10nz*/)
    primesya_T404_Main_T404_Main_V_4_GP = (1+primesya_T404_Main_T404_Main_V_4_GP);
}

 void primesya::exe6210()
 { 
  //  Method no 62 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP+primesya_T404_Main_T404_Main_V_2_GP<1000&&xpc10nz==17/*17:xpc10nz*/)
    primesya_T404_Main_T404_Main_V_4_GP = (primesya_T404_Main_T404_Main_V_2_GP+primesya_T404_Main_T404_Main_V_2_GP);
}

 void primesya::exe6310()
 { 
  //  Method no 63 mname=primesya
    if (primesya_T404_Main_T404_Main_V_2_GP+primesya_T404_Main_T404_Main_V_2_GP>=1000&&xpc10nz==17/*17:xpc10nz*/)
    primesya_T404_Main_T404_Main_V_4_GP = (primesya_T404_Main_T404_Main_V_2_GP+primesya_T404_Main_T404_Main_V_2_GP);
}

 void primesya::exe6410()
 { 
  //  Method no 64 mname=primesya
    if (primesya_T404_Main_T404_Main_V_4_GP>=1000&&xpc10nz==18/*18:xpc10nz*/)
    primesya_T404_Main_T404_Main_V_2_GP = (1+primesya_T404_Main_T404_Main_V_2_GP);
}

 void primesya::exe6510()
 { 
  //  Method no 65 mname=primesya
    if (xpc10nz==19/*19:xpc10nz*/)
    __BOOL_CC_SCALbx10_ARA0_WRD0 = (0x0);
}

 void primesya::exe6610()
 { 
  //  Method no 66 mname=primesya
    if (xpc10nz==19/*19:xpc10nz*/)
    __BOOL_CC_SCALbx10_ARA0_AD0 = (primesya_T404_Main_T404_Main_V_4_GP);
}

 void primesya::exe6710()
 { 
  //  Method no 67 mname=primesya
    if (xpc10nz==19/*19:xpc10nz*/)
    primesya_T404_Main_T404_Main_V_4_GP = (primesya_T404_Main_T404_Main_V_2_GP+primesya_T404_Main_T404_Main_V_4_GP);
}

 void primesya::exe6810()
 { 
  //  Method no 68 mname=primesya
    if (xpc10nz==21/*21:xpc10nz*/)
    __BOOL_CC_SCALbx10_ARA0_WRD0 = (0x1);
}

 void primesya::exe6910()
 { 
  //  Method no 69 mname=primesya
    if (xpc10nz==21/*21:xpc10nz*/)
    __BOOL_CC_SCALbx10_ARA0_AD0 = (primesya_T404_Main_T404_Main_V_2_GP);
}

 void primesya::exe7010()
 { 
  //  Method no 70 mname=primesya
    if (xpc10nz==21/*21:xpc10nz*/)
    primesya_T404_Main_T404_Main_V_2_GP = (1+primesya_T404_Main_T404_Main_V_2_GP);
}

 void primesya::exe7110()
 { 
  //  Method no 71 mname=primesya
    if (xpc12nz==5/*5:xpc12nz*/)
    xpc12nz = (1/*1:xpc12nz*/);
}

 void primesya::exe7210()
 { 
  //  Method no 72 mname=primesya
    if (xpc12nz==4/*4:xpc12nz*/)
    xpc12nz = (5/*5:xpc12nz*/);
}

 void primesya::exe7310()
 { 
  //  Method no 73 mname=primesya
    if (xpc12nz==3/*3:xpc12nz*/)
    xpc12nz = (4/*4:xpc12nz*/);
}

 void primesya::exe7410()
 { 
  //  Method no 74 mname=primesya
    if (!pio_hwen&&xpc12nz==1/*1:xpc12nz*/)
    xpc12nz = (3/*3:xpc12nz*/);
}

 void primesya::exe7510()
 { 
  //  Method no 75 mname=primesya
    if (xpc12nz==2/*2:xpc12nz*/)
    xpc12nz = (4/*4:xpc12nz*/);
}

 void primesya::exe7610()
 { 
  //  Method no 76 mname=primesya
    if (pio_hwen&&xpc12nz==1/*1:xpc12nz*/)
    xpc12nz = (2/*2:xpc12nz*/);
}

 void primesya::exe7710()
 { 
  //  Method no 77 mname=primesya
    if (xpc12nz==0/*0:xpc12nz*/)
    xpc12nz = (1/*1:xpc12nz*/);
}

 void primesya::exe7810()
 { 
  //  Method no 78 mname=primesya
    SINTCCSCALbx12ARA0RRh10shot0 = (!pio_hwen&&xpc12nz==1/*1:xpc12nz*/);
}

 void primesya::exe7910()
 { 
  //  Method no 79 mname=primesya
    __SINT_CC_SCALbx12_ARA0_WEN0 = (((pio_hwen&&xpc12nz==1/*1:xpc12nz*/)?pio_hwen:0));
}

 void primesya::exe8010()
 { 
  //  Method no 80 mname=primesya
    __SINT_CC_SCALbx12_ARA0_REN0 = (!pio_hwen&&xpc12nz==1/*1:xpc12nz*/);
}

 void primesya::exe8110()
 { 
  //  Method no 81 mname=primesya
    if (SINTCCSCALbx12ARA0RRh10shot0)
    SINTCCSCALbx12ARA0RRh10hold = (__SINT_CC_SCALbx12_ARA0_RDD0);
}

 void primesya::exe8210()
 { 
  //  Method no 82 mname=primesya
    if (BOOLCCSCALbx10ARA0RRh10shot0)
    BOOLCCSCALbx10ARA0RRh10hold = (__BOOL_CC_SCALbx10_ARA0_RDD0);
}

 void primesya::exe8310()
 { 
  //  Method no 83 mname=primesya
    if (!pio_hwen&&xpc12nz==1/*1:xpc12nz*/)
    __SINT_CC_SCALbx12_ARA0_AD0 = (pio_addr);
}

 void primesya::exe8410()
 { 
  //  Method no 84 mname=primesya
    if (!pio_hwen&&xpc12nz==3/*3:xpc12nz*/)
    pio_rdata = ((int)(((xpc12nz==3/*3:xpc12nz*/)?__SINT_CC_SCALbx12_ARA0_RDD0:SINTCCSCALbx12ARA0RRh10hold)));
}

 void primesya::exe8510()
 { 
  //  Method no 85 mname=primesya
    if (pio_hwen&&xpc12nz==1/*1:xpc12nz*/)
    __SINT_CC_SCALbx12_ARA0_WRD0 = ((int)(pio_wdata));
}

 void primesya::exe8610()
 { 
  //  Method no 86 mname=primesya
    if (pio_hwen&&xpc12nz==1/*1:xpc12nz*/)
    __SINT_CC_SCALbx12_ARA0_AD0 = (pio_addr);
}

 void primesya::exe012()
 { 
  //  Method no 0 mname=@_BOOL/CC/SCALbx10_ARA0.RAM
    if (__BOOL_CC_SCALbx10_ARA0_WEN0)
    __BOOL_CC_SCALbx10_ARA0[__BOOL_CC_SCALbx10_ARA0_AD0] = (__BOOL_CC_SCALbx10_ARA0_WRD0);
}

 void primesya::exe112()
 { 
  //  Method no 1 mname=@_BOOL/CC/SCALbx10_ARA0.RAM
    __BOOL_CC_SCALbx10_ARA0_RDD0 = (__BOOL_CC_SCALbx10_ARA0[__BOOL_CC_SCALbx10_ARA0_AD0]);
}

 void primesya::exe212()
 { 
  //  Method no 2 mname=@_BOOL/CC/SCALbx10_ARA0.RAM
// Resource=SRAM iname=i_@_BOOL/CC/SCALbx10_ARA0 10x1 clk=posedge(clk) synchronous/pipeline=1 no_ports=1 <NONE> used by threads xpc10
}

 void primesya::exe010()
 { 
  //  Method no 0 mname=@_SINT/CC/SCALbx12_ARA0.RAM
    if (__SINT_CC_SCALbx12_ARA0_WEN0)
    __SINT_CC_SCALbx12_ARA0[__SINT_CC_SCALbx12_ARA0_AD0] = (__SINT_CC_SCALbx12_ARA0_WRD0);
}

 void primesya::exe110()
 { 
  //  Method no 1 mname=@_SINT/CC/SCALbx12_ARA0.RAM
    __SINT_CC_SCALbx12_ARA0_RDD0 = (__SINT_CC_SCALbx12_ARA0[__SINT_CC_SCALbx12_ARA0_AD0]);
}

 void primesya::exe210()
 { 
  //  Method no 2 mname=@_SINT/CC/SCALbx12_ARA0.RAM
// Resource=SRAM iname=i_@_SINT/CC/SCALbx12_ARA0 10x32 clk=posedge(clk) synchronous/pipeline=1 no_ports=1 <NONE> used by threads xpc12
}
// eof primesya
