// primesya
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18a : 5th-December-2016 Unix 3.13.0.65// 10/02/2017 17:08:09
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe csharp/primes_offchip.exe -res2-loadstore-port-count=0 -vnl=primes_offchip.v -vnl-rootmodname=primes_offchip csharp/KSubs2_Director.dll -vnl-resets=synchronous -kiwic-finish=disable -vnl-roundtrip=disable -kiwic-register-colours=1 -bevelab-default-pause-mode=bblock -fp-fl-sp-mul=4

#ifndef primesya_H
#define primesya_H
#define HPR_NEEDS_SYSTEMC 1
#include "hprls.h"
// opath operation: 10: cgen2

struct  primesya  : public sc_module
{
  unsigned int primesya_T404_Main_T404_Main_V_2_GP;
  unsigned int primesya_T404_Main_T404_Main_V_4_GP;
  sc_uint<5> xpc10nz;
  sc_uint<1> BOOLCCSCALbx10ARA0RRh10hold;
  sc_uint<1> BOOLCCSCALbx10ARA0RRh10shot0;
  sc_uint<3> xpc12nz;
  unsigned int SINTCCSCALbx12ARA0RRh10hold;
  sc_uint<1> SINTCCSCALbx12ARA0RRh10shot0;
  sc_out  < unsigned int > design_serial_number;
  sc_in < unsigned int > pio_addr;
  sc_in < unsigned int > pio_wdata;
  sc_out  < unsigned int > pio_rdata;
  sc_in < sc_uint<1> > pio_hwen;
  sc_in < unsigned int > volume;
  sc_out  < unsigned int > count;
  sc_out  < unsigned int > elimit;
  sc_out  < unsigned int > evariant;
  sc_out  < unsigned int > edesign;
  sc_out  < sc_uint<1> > finished;
  sc_uint<1> __BOOL_CC_SCALbx10_ARA0[10];
  sc_uint<1> __BOOL_CC_SCALbx10_ARA0_RDD0;
  sc_uint<4> __BOOL_CC_SCALbx10_ARA0_AD0;
  sc_uint<1> __BOOL_CC_SCALbx10_ARA0_WEN0;
  sc_uint<1> __BOOL_CC_SCALbx10_ARA0_REN0;
  sc_uint<1> __BOOL_CC_SCALbx10_ARA0_WRD0;
  unsigned int __SINT_CC_SCALbx12_ARA0[10];
  sc_in < sc_uint<1> > clk;
  sc_in < sc_uint<1> > reset;
  unsigned int __SINT_CC_SCALbx12_ARA0_RDD0;
  sc_uint<4> __SINT_CC_SCALbx12_ARA0_AD0;
  sc_uint<1> __SINT_CC_SCALbx12_ARA0_WEN0;
  sc_uint<1> __SINT_CC_SCALbx12_ARA0_REN0;
  unsigned int __SINT_CC_SCALbx12_ARA0_WRD0;

  primesya( sc_core::sc_module_name name)  :    sc_core::sc_module("primesya")
   { 
       SC_HAS_PROCESS(primesya);
SC_METHOD(new SystemCsharp.sc_method_t(exe8610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe214)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe114)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe014)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe212));
SC_METHOD(new SystemCsharp.sc_method_t(exe112)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe012)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe210));
SC_METHOD(new SystemCsharp.sc_method_t(exe110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe010)).sensitive_pos(clk);
  }

   void exe014();

   void exe114();

   void exe214();

   void exe310();

   void exe410();

   void exe510();

   void exe610();

   void exe710();

   void exe810();

   void exe910();

   void exe1010();

   void exe1110();

   void exe1210();

   void exe1310();

   void exe1410();

   void exe1510();

   void exe1610();

   void exe1710();

   void exe1810();

   void exe1910();

   void exe2010();

   void exe2110();

   void exe2210();

   void exe2310();

   void exe2410();

   void exe2510();

   void exe2610();

   void exe2710();

   void exe2810();

   void exe2910();

   void exe3010();

   void exe3110();

   void exe3210();

   void exe3310();

   void exe3410();

   void exe3510();

   void exe3610();

   void exe3710();

   void exe3810();

   void exe3910();

   void exe4010();

   void exe4110();

   void exe4210();

   void exe4310();

   void exe4410();

   void exe4510();

   void exe4610();

   void exe4710();

   void exe4810();

   void exe4910();

   void exe5010();

   void exe5110();

   void exe5210();

   void exe5310();

   void exe5410();

   void exe5510();

   void exe5610();

   void exe5710();

   void exe5810();

   void exe5910();

   void exe6010();

   void exe6110();

   void exe6210();

   void exe6310();

   void exe6410();

   void exe6510();

   void exe6610();

   void exe6710();

   void exe6810();

   void exe6910();

   void exe7010();

   void exe7110();

   void exe7210();

   void exe7310();

   void exe7410();

   void exe7510();

   void exe7610();

   void exe7710();

   void exe7810();

   void exe7910();

   void exe8010();

   void exe8110();

   void exe8210();

   void exe8310();

   void exe8410();

   void exe8510();

   void exe8610();

   void exe012();

   void exe112();

   void exe212();

   void exe010();

   void exe110();

   void exe210();
};

#endif
// eof primesya
